### ISSUE TITLE
Parameterized Icon Sets

### ISSUE THREAD

**Issue by brianfeister** [klarsys/angular-material-icons#10]
Would you be willing to accept a parameterized icon set similar to [`$mdIconProvider`](https://material.angularjs.org/#/api/material.components.icon/service/$mdIconProvider)?  I would prefer to avoid including this library if it's going to inject a 200kb file that I don't have the ability to scale down for my specific build.

**Comment by urmilparikh** [comment]
Sure, do you have something handy? We can look at it and pull.
