### ISSUE TITLE
The directive should replace it´s self with the svg element

### ISSUE THREAD

**Issue by ahmedalejo** [klarsys/angular-material-icons#11]
First shoutout: great work with this compilation and for thoughtful SVG-morpheus integration

To improve styling the svg element the SVG should not be wrapped in the , for example alignment isn´t quite possible while svg is hosted in the "ng-md-icon" element

**Comment by urmilparikh** [comment]
You mean adding `replace: true`?
If possible, please send a plunker or so with alignment issue you are facing.

**Comment by coryasilva** [comment]
I think the replace feature is deprecated.
