### ISSUE TITLE
Sidenav Burger not displayed correctly

### ISSUE THREAD

**Issue by martinbrylski** [klarsys/angular-material-icons#12]
Using the example of the original angular-material but using ng-md-icon for the burger svg causes to display it wrong vertically aligned.

Comparing the svg parameters of both svg elements there are some differences:
md-icon:
```
<svg ... x="0px" y="0px" width="100%" height="100%" viewBox="0 0 24 24" enable-background="new 0 0 24 24" xml:space="preserve" fit="" preserveAspectRatio="xMidYMid meet" style="pointer-events: none; display: block;">...</svg>
```
ng-md-icon:
```
<svg ... viewBox="0 0 24 24" width="24" height="24">...</svg>
```

If the original attributes are set it displays correctly. Is this a bug or are there other workarounds to get it working?

Thx

**Comment by urmilparikh** [comment]
@martinbrylski, if possible, please share an example / plunker to illustrate the issue.

**Comment by martinbrylski** [comment]
I've used this as template: http://codepen.io/anon/pen/emqrWO
There the burger svg is a little out of vertical center.
Using additional styles of the original css stylesheet for md-icon causing it to align at the very bottom of the text. (Copying and renaming all css expressions of md-icon to ng-md-icon)

**Comment by martinbrylski** [comment]
Ok. It seems there is a general "issue" regarding the styling of `<md-icon>` and `<ng-md-icon>` in several elements (button, list-item, ...). Could you imagine how to solve this to ease the integration in the default angular-material.css?
Is it possible to override an angular directive and so use the default css selectors?

**Comment by urmilparikh** [comment]
It should be possible to override `md-icon` directive. I'll give it a try...

**Comment by urmilparikh** [comment]
It turned out to be super simple.

* Get a local copy of `angular-material-icons.js`.
* Replace `.directive('ngMdIcon', function() ...` with `.directive('mdIcon', function() ...` in it.
* Include the modified version in your html and check if that works for you.
