### ISSUE TITLE
Integrate community-led iconography set

### ISSUE THREAD

**Issue by xenit-raven** [klarsys/angular-material-icons#18]
I would be very interested to see an extension of the icon set using the community-led iconography set [material desgin icons](http://materialdesignicons.com/). The project is updated and extended regularly. Note that the path description of this set is not minimized (many vectors end with .333333334) so this would severly increase the filesize if not handled.

**Comment by urmilparikh** [comment]
I'm planning to integrate only few selected icons from there, let me know if anyone has any choices.
Current list is: amazon, apple, facebook, github, google-plus, hangouts, linkedin, office, twitter, whatsapp, windows.

**Comment by klevecoder** [comment]
Please add also login and logout icons

**Comment by xenit-raven** [comment]
filetype icons would be valuable

**Comment by urmilparikh** [comment]
Added in new release.
@xenit-raven , there were too many of file-type icons, so I have avoided them. Let me know if you are looking for any specific ones.
