### ISSUE TITLE
Uncaught TypeError: a.target.className.indexOf is not a function at bubble_compiled.js:176

### ISSUE THREAD

**Issue by reidlai** [klarsys/angular-material-icons#20]
I try to use md-ng-icon directive inside md-button of Angular Material and button tag of Lumx.  I keep on to receive the following error when I implement ng-click event at md-button or button tag:

Uncaught TypeError: a.target.className.indexOf is not a function
This error message occurred at bubble_compiled.js:176

Here is my template segment:

<md-button class="md-icon-button" aria-label="Menu" ng-click="togglePanel()">
    <ng-md-icon icon="menu" size="54"></ng-md-icon>
</md-button>

**Comment by urmilparikh** [comment]
You forgot to attach template segment?
It will help if you can send a Plunker.

**Comment by reidlai** [comment]
template segment?

Here is my code

<md-button class="md-icon-button" ng-click="showMarketThemeDetail(MarketTheme.id)" aria-label="More">
  <ng-md-icon icon="arrow_forward" size="24"></ng-md-icon>
</md-button>

I can go to ui-router state after click but error message always come out.  Any help?

**Comment by urmilparikh** [comment]
Can you reproduce by forking this?
http://plnkr.co/edit/37No9RsPNLZcDlQYoXqm?p=preview

**Comment by urmilparikh** [comment]
Closing this for no follow-ups.
