### ISSUE TITLE
Please release again to fix Angular 1.4 dependency

### ISSUE THREAD

**Issue by mcasimir** [klarsys/angular-material-icons#21]
Hi buddy, 
the current release of `angular-material-icons` still has angular 1.3 dependency.
You have to release again to let bower read the new dep allowing angular 1.4.

Although it is not a big deal for `bower` and `npm` it breaks dependencies for rails apps that uses https://rails-assets.org/

**Comment by urmilparikh** [comment]
Done. Published a new version.

**Comment by QuantumInformation** [comment]
What is the latest version on cdn?
