### ISSUE TITLE
[FEATURE REQUEST] Add option to align icon to center of containing element 

### ISSUE THREAD

**Issue by QuantumInformation** [klarsys/angular-material-icons#23]
It would be nice to add an option to align icon to the center of containing element.

![image](https://cloud.githubusercontent.com/assets/216566/8376843/53aa3db4-1c03-11e5-82d3-62c7d94df729.png)

This would make it easier to align with other inline items:
![image](https://cloud.githubusercontent.com/assets/216566/8376857/8cc100ce-1c03-11e5-865b-976f12e2da26.png)

**Comment by RomFouq** [comment]
I really agree. This vertical alignment is annoying.

**Comment by QuantumInformation** [comment]
Great workaround! Works in all cases in my app!

**Comment by urmilparikh** [comment]
Closing it, since css workaround in #15 is working.
