### ISSUE TITLE
ng-md-icon cannot vertical align middle while in the md-fab

### ISSUE THREAD

**Issue by januslo** [klarsys/angular-material-icons#24]
I found ng-md-icon cannot vertical align middle while in the md-fab as the code i wrote:
```javascript
<md-button class="md-fab md-primary md-fab-bottom-right" ng-href="tel:{{nativeInfo.customerPhone}}">
    <ng-md-icon icon="call" style="fill:white" size="20"></ng-md-icon>
</md-button>
```
After Intercepted the html code generated, I found the inner svg element has no any display property set. I tried to fix this by adding the "display:block" as the css following:

.md-button.md-fab ng-md-icon svg{
	display: block;
}

May I have your confirmation or suggestion ?

**Comment by QuantumInformation** [comment]
Please see this issue for workaround:

https://github.com/klarsys/angular-material-icons/issues/15

**Comment by januslo** [comment]
@QuantumInformation it works for me, after tested, I found "line-height:1" is enough for this issue. as the code:
ng-md-icon {
	/**/
	/*fill: currentColor;*/
	/*vertical-align: middle;*/
	/*display: inline-block;*/
	line-height: 1;
}
anyway, let's close this for this issue maybe the same as the #15 .
