### ISSUE TITLE
ng-md-icon inside md-button not centered

### ISSUE THREAD

**Issue by emps** [klarsys/angular-material-icons#32]
ng-md-icon inside md-button not centered like normal md-icon in md-button

**Comment by urmilparikh** [comment]
Pulled #33 as fix for this issue.

**Comment by nareshbhatia** [comment]
I couldn't find any documentation for `angular-material-icons.css`. I assume that this should be included in our apps. Without it, this issue was not working for me (obviously, because the fix is in that file). I wonder why it is not included in index.html of the demo app).
