### ISSUE TITLE
Runtime error when using latest commit

### ISSUE THREAD

**Issue by nareshbhatia** [klarsys/angular-material-icons#34]
I need the fix for issue #33. Since this issue is not in the latest v0.5, I am including the latest from github:

https://github.com/klarsys/angular-material-icons.git#c1a75b690d9dfd6d681f7d1c74f8ef9275b046a7

However including this version is giving me a runtime error:

[$injector:strictdi] function(ngMdIconService) is not using explicit annotation and cannot be invoked in strict mode

Please help.

**Comment by nareshbhatia** [comment]
Tried the latest commit. Still getting the same issue. Here's the line in my bower.json:

    "angular-material-icons": "https://github.com/klarsys/angular-material-icons.git#576768adb4ef898f6739c2b3c26e85c617ec9977"

Am I doing something wrong? Do I have to do a local build or something like that?

**Comment by urmilparikh** [comment]
@nareshbhatia, I need some way to reproduce the issue.

Can you checkout separately in a new folder, open index.html and see if the problem can be reproduced? Feel free to modify (and share) index.html / demo.js as required to reproduce issue.

It will be better if you can create a plunkr with the issue.

**Comment by nareshbhatia** [comment]
index.html/demo.js work perfectly fine in a fresh checkout to a local repository. Trying to investigate what's happening in my Angular Material app. Will post a plunkr with the issue.

Thanks.

**Comment by nareshbhatia** [comment]
I created pull request #35 to solve this issue. The problem is that the library and the demo do not use proper annotations and hence do not work in ng-strict-di mode. This would prevent the library to work correctly when compacted. Pull request #35 fixes this problem.

**Comment by urmilparikh** [comment]
Thank you! I have pulled #35.
