### ISSUE TITLE
JSHint errors

### ISSUE THREAD

**Issue by nareshbhatia** [klarsys/angular-material-icons#36]
JSHint is currently reporting 22 errors (see below). These should be fixed. I recommend introducing a simple gulp script that can be run before checking in any code. See https://github.com/archfirst/angular-material-template for my preferred setup. If you'd like, I can set this up and send a pull request.

    $ jshint *.js
    angular-material-icons.js: line 7, col 1, Use the function form of "use strict".
    angular-material-icons.js: line 83, col 10, Missing semicolon.
    angular-material-icons.js: line 9, col 1, 'angular' is not defined.
    angular-material-icons.js: line 61, col 29, 'SVGMorpheus' is not defined.
    angular-material-icons.js: line 109, col 22, 'angular' is not defined.

    angular-material-icons.min.js: line 276, col 405, Expected an assignment or function call and instead saw an expression.
    angular-material-icons.min.js: line 277, col 176, Expected an assignment or function call and instead saw an expression.
    angular-material-icons.min.js: line 277, col 177, Missing semicolon.
    angular-material-icons.min.js: line 277, col 300, Missing semicolon.
    angular-material-icons.min.js: line 277, col 304, Missing semicolon.
    angular-material-icons.min.js: line 277, col 416, Expected an assignment or function call and instead saw an expression.
    angular-material-icons.min.js: line 277, col 417, Missing semicolon.
    angular-material-icons.min.js: line 278, col 18, Expected an assignment or function call and instead saw an expression.
    angular-material-icons.min.js: line 278, col 19, Missing semicolon.
    angular-material-icons.min.js: line 278, col 58, Expected an assignment or function call and instead saw an expression.
    angular-material-icons.min.js: line 278, col 100, Expected an assignment or function call and instead saw an expression.
    angular-material-icons.min.js: line 278, col 215, Missing semicolon.
    angular-material-icons.min.js: line 278, col 256, Expected an assignment or function call and instead saw an expression.
    angular-material-icons.min.js: line 278, col 294, Expected an assignment or function call and instead saw an expression.
    angular-material-icons.min.js: line 278, col 295, Missing semicolon.
    angular-material-icons.min.js: line 278, col 297, Missing semicolon.

    demo.js: line 19, col 10, Missing semicolon.

    22 errors

**Comment by urmilparikh** [comment]
Please send a pull request.
I assume angular-material-icons.min.js will then be generated through gulp script?

**Comment by nareshbhatia** [comment]
That's correct. Working on a PR.

**Comment by nareshbhatia** [comment]
Created pull request #37 for this. It addresses JSHint errors only. I have suppressed 2 errors, which are more involved to fix. In general, it is always good to pay attention to these.

Don't have time right now for minification. Will try to do it later. I would prefer to rearrange the directory structure for that. Create a `src` directory to keep only the source, so that minified file can be put into a `build` directory. Also examples/demos should go in a different directory (not `src`).

**Comment by urmilparikh** [comment]
Sure. #37 is merged.
