### ISSUE TITLE
doen't play nice with ngMaterial

### ISSUE THREAD

**Issue by alzalabany** [klarsys/angular-material-icons#39]
ngMaterial use has its own `<md-icon>` directive, and most of its components and css are setup for it.
when using ng-md-icon styling for icons are goan.

example: 

```
<md-list>
        <md-list-item ng-repeat="item in menu" role="link" md-ink-ripple>
          <ng-md-icon icon="{{item.icon}}" aria-label="{{item.title}}"></ng-md-icon>
          <p>{{item.title}}</p>
        </md-list-item>
        <md-divider></md-divider>
        
      </md-list>
```

no padding or margin will be applied on ng-md-icon.

**Comment by urmilparikh** [comment]
Discussion in #15 will help you.
