### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by manikantag** [klarsys/angular-material-icons#4]
I know this is happily supported in Chrome, Firefox and all other evergreen browsers. What about IE8/IE9? Thanks.

**Comment by harik-klar** [comment]
IE8 is not supported by Angular 1.3, so that definitely won't work.  On IE9, it works, but [SVG-Morpheus](http://alexk111.github.io/SVG-Morpheus/) doesn't.  So you can see the icons, but not the cool animations.

**Comment by urmilparikh** [comment]
Also note the one should use `ng-attr-style` for IE support. I have updated the demo page with this information.
