### ISSUE TITLE
google/material-design-icons update

### ISSUE THREAD

**Issue by kuzman** [klarsys/angular-material-icons#44]
Hi,

Do you plan to update to the latest version of google/material-design-icons? The 2.1 update says that 96 new icons have been added. One of the forks even have the update: https://github.com/dresslerit/angular-material-icons/tree/google-icon-v2.1-update

Thanks!

**Comment by aaronkantrowitz** [comment]
This is a great icon pack. I would also like to know when this will be updated. I'm waiting to use some of the new icons and like using the angular directives to accomplish this.

**Comment by dresslerit** [comment]
Hi, I've created an pull request (#43) some time ago. I am just waiting until the request is merged.

**Comment by urmilparikh** [comment]
Thank you, @dresslerit, I have merged your pull request.
