### ISSUE TITLE
Person_pin & gh-pages update

### ISSUE THREAD

**Issue by dresslerit** [klarsys/angular-material-icons#45]
First, I'm sorry but I forget to exec the build command, so the min file has currently not the person_pin.

Secondly, I'm currently changing the array at gh-pages because they dont show the new icons. Its in progress.

Greetings Noah

**Comment by urmilparikh** [comment]
Don't worry, I'll run the build command and update gh-pages during next release. I also need to update README for #42 as part of next update.

**Comment by dresslerit** [comment]
Ok thanks

**Comment by dresslerit** [comment]
See Commits
