### ISSUE TITLE
Is there any reason why this error is swallowed without logging ?

### ISSUE THREAD

**Issue by HarishAtGitHub** [klarsys/angular-material-icons#48]
In this statement 
https://github.com/klarsys/angular-material-icons/blob/v0.6.0/angular-material-icons.js#L68-L72

error is swallowed without logging. this made my debugging difficult today.

today I made a blunder of enclosing the attributes of json in the options attribute within single quotes
(which is not allowed as per json rules) so my JSON.parse failed.

as this was so silent(due to swallowing) I could not find the reason without putting a debug point. Had you logged the error it would have been easier to debug .

Is there any reason why this error is swallowed without logging ?

**Comment by urmilparikh** [comment]
The idea is to use SVGMorpheus if it is available.
If not, fallback to simple icon replacement.

**Comment by urmilparikh** [comment]
Please confirm if this change is good.
