### ISSUE TITLE
[Question] Is there a way to add my own custom icon

### ISSUE THREAD

**Issue by cmacdonnacha** [klarsys/angular-material-icons#53]
Let's say I have my own icon stored in my assets folder. Could I load my icon from there? 

    <md-icon icon="src/assets/logo.png" ></md-icon>

Sort of like what Angualr Material have for their icons:

    <md-icon md-svg-icon="img/icons/menu.svg"></md-icon>

**Comment by dresslerit** [comment]
Yes, you can use the ngMdIconServiceProvider. 

app.config(['ngMdIconServiceProvider'], function (ngMdIconServiceProvider) {
    ngMdIconServiceProvider.addShapes({
        yourName: "content of SVG exclude the SVG-TAG"
    })
})

//Usage
<ng-md-icon icon="yourName"></ng-md-icon>

**Comment by cmacdonnacha** [comment]
Great. Can I add ".png" images as well? Or is it restricted to SVG?

**Comment by dresslerit** [comment]
I'm sorry, only SVG because the code wraps the content into an SVG tag. 

Von meinem iPhone gesendet

**Comment by cmacdonnacha** [comment]
Cool, no problem thanks. Does really make sense to use a png image as an icon anyway.
