### ISSUE TITLE
New release needed

### ISSUE THREAD

**Issue by codershop** [klarsys/angular-material-icons#56]
I need to use some material icons that are not in the latest release.  All the icons I need are already on the master branch.  I just need a new release created so that I can use them through npm.

**Comment by urmilparikh** [comment]
It will come in a couple of days, need to close open issues and merge PRs.

**Comment by tashoecraft** [comment]
@urmilparikh Is the new release coming soon? There is a whole bunch of missing icons. Trying to use some of the social (mood_bad, any of the satisfied) but they are all missing.

**Comment by yulin-dong** [comment]
'feedback' icon is missing from the latest release, though it is shown up in the demo page https://klarsys.github.io/angular-material-icons/

**Comment by bayy** [comment]
'feedback' icon is missing from the latest release, though it is shown up in the demo page https://klarsys.github.io/angular-material-icons/

**Comment by ethanmick** [comment]
Yes, just ran into this. Took a while to realize why icons weren't loading. Please cut a new release!

**Comment by urmilparikh** [comment]
It is there... CDN may take a day to update.

**Comment by ethanmick** [comment]
Thank you!
