### ISSUE TITLE
picture_as_pdf icon does not work.

### ISSUE THREAD

**Issue by prerna12** [klarsys/angular-material-icons#57]
Hi when I am trying to use picture_as_pdf icon I am unable to see the icon. It shows a 'question mark'.

Here is my one line code
`<ng-md-icon` ng-if="isPdf" `icon="picture-as-pdf"></ng-md-icon>`

Can you tell me the correct string name for using pdf icon?

**Comment by dresslerit** [comment]
Use picture_as_pdf.

**Comment by urmilparikh** [comment]
Thank you, @dresslerit !
