### ISSUE TITLE
Icon is not centered inside <md-button>

### ISSUE THREAD

**Issue by cmacdonnacha** [klarsys/angular-material-icons#58]
Please see [demo](http://codepen.io/cmacdonnacha/pen/KzdWMm)

The icon should be centered inside the **md-button**.

![image](https://cloud.githubusercontent.com/assets/9777763/13529120/44d943c2-e212-11e5-8ad1-576fc5d4ea0d.png)

**Comment by urmilparikh** [comment]
Please insert `angular-material-icons.css` in your project and check if that helps.

**Comment by cmacdonnacha** [comment]
@urmilparikh Thanks for your suggestion but it still didn't work.

**Comment by urmilparikh** [comment]
I copy-pasted it in your pen and it seems to work: http://codepen.io/anon/pen/KzVWdg

**Comment by cmacdonnacha** [comment]
Ah ok, I tried it my project and didn't seem to work. If it works in the codepen then it's not an issue. Thanks.
