### ISSUE TITLE
angular-material-icons.min.js broken in bower repo

### ISSUE THREAD

**Issue by aeroxy** [klarsys/angular-material-icons#6]
The current `angular-material-icons.min.js` in bower repo is broken.

**Comment by aeroxy** [comment]
Also in github/npm repo (would assume they be the same) btw.

**Comment by urmilparikh** [comment]
@aeroxy, I do not see any issue, please elaborate exactly what issue are you facing.

**Comment by aeroxy** [comment]
@urmilparikh Sorry I posted at the wrong repo. >.< Sorry sorry sorry. I am super embarrassed.
