### ISSUE TITLE
Icon disappear after md-fab-toolbar collapse

### ISSUE THREAD

**Issue by JGeraldoLima** [klarsys/angular-material-icons#60]
Hi, I'm having this problem and I do not have ideia about how to solve this.

I have an md-fab-toolbar as an md-card header, using "menu" icon but when the toolbar collapses, the icon disappear. Does somebody knows whats is going on?

![captura de tela de 2016-04-28 11 46 33](https://cloud.githubusercontent.com/assets/6726996/14889923/0f8d8516-0d37-11e6-974d-6b95ca276b1d.png)

then:

![captura de tela de 2016-04-28 11 48 21](https://cloud.githubusercontent.com/assets/6726996/14889957/2cf0c3a2-0d37-11e6-8d70-a6eeea6c3b22.png)

then:

![captura de tela de 2016-04-28 11 49 03](https://cloud.githubusercontent.com/assets/6726996/14889982/427b9008-0d37-11e6-8d3c-602621bffa5c.png)

Even when I click again, the icon does not appear anymore, I need to refresh the page to do so

**Comment by dresslerit** [comment]
Can you make a Codepen or a JSfiddle for us to analyze the problem ?

**Comment by JGeraldoLima** [comment]
Here we go: http://codepen.io/jgeraldo/pen/xVQpwd

I changed line 18 to be able to use your lib. The icon is out of align but it is not important, I could fix it in my page but I forgot how :p

**Comment by mennya** [comment]
In your Codepen change this line `<ng-md-icon icon="menu"></ng-md-icon>` to `<md-icon ng-md-icon icon="menu"></md-icon>`.

**Comment by raziza** [comment]
They are kind of forcing us to use `md-icon` tag inside. One Workaround I've found is still to use this tag and canceling the display style.
```
<md-icon ng-md-icon style="display: unset">
    <!-- Put what ever youwant here -->
    <span class="glyphicon glyphicon-menu-hamburger"></span>
</md-icon>
```
