### ISSUE TITLE
Should not be loading Angular Material CSS

### ISSUE THREAD

**Issue by isherwood** [klarsys/angular-material-icons#76]
I just spent hours spelunking through our various app builds trying to find out why a very old version of AM's CSS was landing in my combined CSS file. Turns out it's in this module's CSS file. Not good. 

Please remove it and make it an external dependency.

**Comment by urmilparikh** [comment]
Using CSS file is optional. It takes care of alignment issues many users reported long time back.

**Comment by isherwood** [comment]
Thank you. Yes, I realized that right after I opened the issue. It's very out of date, though, which is what caused my issues.
