### ISSUE TITLE
does not work with md-input-container icon

### ISSUE THREAD

**Issue by capgeti** [klarsys/angular-material-icons#8]
Hi, ng-md-icon is not working with input icons:

normaly from material angularjs:
```html
 <md-input-container md-no-float>
      <md-icon md-svg-src="/demo-partials/input/demoIcons/icons/ic_phone_24px.svg"></md-icon>
      <input ng-model="user.phone" type="text" placeholder="Phone Number">
  </md-input-container>
```
with  icons:
```html
<md-input-container md-no-float>
      <ng-md-icon icon="phone"></ng-md-icon>
      <input ng-model="user.phone" type="text" placeholder="Phone Number">
  </md-input-container>
```
because the ng-md-icon is not the mg-icon element for material styles.
is there a solution for?

**Comment by urmilparikh** [comment]
You can get closer by adding some css.
Take a look at `<style>...</style>` in http://plnkr.co/edit/PzMKpgiYvhppDGaeBfN6?p=preview

**Comment by urmilparikh** [comment]
@capgeti, you may be interested in hack described in #12.
